subdomain: properly check that a DNS zone has no more records inside
threefoldtech/tfgateway pull request #29
Opened 2020-09-23 13:01 UTC by zaibon

fixes #28

2020-09-23 14:07 UTC, LeeSmet requested changes

2020-09-23 14:07 UTC, LeeSmet commented on dns/dns_zone.go
> +			return true
s/true/false ?

2020-09-23 14:41 UTC, zaibon commented on dns/dns_zone.go
> +			return true
woopsy

2020-09-24 08:31 UTC, LeeSmet requested changes
code looks good but tests are failing for some reason

2020-09-24 08:40 UTC, merged